var GAME_LEVELS = [
  ["                                                                                   ",
   "                     f              o           x x x xxx     o                    ",
   "                    xx   x x   x     x     xyx            x       x                ",
   "                xxx                   x!!x        o             yx                  ",
   "            xx                        x!!x                                          ",
   "       xx                             x!!x                                          ",
   "           xx  xxx  yx                xxxx                        x x               ",
   "                  xx                             xxx      xx    xx!xx               ",
   "                   xxx              o o      xx                  x!!!x              ",
   "                                                                 xx!xx              ",
   "                         xx          xxxxx                        xvx               ",
   "                     xx!!                               xx                      xx  ",
   "  xx               xxx !!                      o o                                x ",
   "  x           a  xx   !!  o                                                    x    ",
   "  x          xxx     !!  xxx                   xxxxx               ff               ",
   "  x          xx        !!                                                   x       ",
   "  x  @   f    x         !!              f                     a     xxxxx       x    ",
   "  xxxxxxxxxxxx  xxxxxxx!!xxxxxx   xxxxxxx      xxxxx       xxxxxxx   xxxxxxxxx      ",
   "                      x!!x      x   x   x     x          x     x                    ",
   "                      x!!x      x!!!x  x    o   x         x!!!!!x                   ",
   "                              x!!!x   xx        xx       x!!!!!x                    ",
   "                              xxxxx  xxx  xyx   xxx       xxxxxxx                   ",
   "                                      xx        xx  o                               ",
   "                                       x !!!!!! x   xx x             ff             "],
    


  
 
  ["                                      x!!xxxxxxx    xx            xxxxxxx                                    x!x      ",
   "                                      x!!x  f                  xxxx     xxxx                                 x!x      ",
   "                                      x!!xxxxxxxxxx           xx           xx                                x!x      ",
   "                                      xx!!!!!!!!!!xx         xx             xx                               x!x      ",
   "       @      xx                         xxxxxxxxxx!!xxyyxx                                                        x!x",
   "       xx         xx             xx             xx!x              o                             a          xx!x       ",
   "      xxx         xxx      x            x       x!x                                         xxxxxxxxxx  xxx!!x        ",
   "      xxx         xxx      xx           xx       xvx    xx    x     xx  x   xx   x   yyy          !!!!!!!!!!!!!!xx     ",
   "       xx    o    xx       xxx    o    xxx                      xx  |   |   |  xx            xxxxxxxx!!!!!xxxxxxxxx   ",
   "        x         x         xx         xx                       xx!!!!!!!!!!!xx            v         x!!!x            ",
   "         xx     xx            x       x                       xxxx!!!!!xxxx                          x!!!x            ",
   "                                               x     x    xx      xxxxxxx        xxx         xxx     x!!!x            ",
   "                                  f            x     x                           x x         x x      x!x             ",
   "             f                   yyy       xx  x     xx                            x         x        x!x             ",
   "                                               x     x                             xx        x                        ",
   "                                      xx       xx    x  xx                         x                                  ",
   "                                               x     x      o  o     x   x     f   x         xx                       ",
   "               x   xx        xxx   xxx      x x     x               x   x         x         x  xxx                    ",
   "              x      xx         x   x          x     x     xxxxxx    x   x   xxxxxxxxx       x   xxx     x  x         ",
   "             xx       xx        x   x    xx     x    xx               x   x   x               x     xx  xx    x        ",
   "             x   x     x        x   x          x     x               x   x   x               x      x!!x       x      ",
   "    x x  f   x         x        x   x          x     x               x   xxxxx   xxxxxx      x      x!!x     xx       ",
   "    x x  x  x    o  x  x       xx   xx         x     x               x           x x          x     x!!x    x         ",
   "!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!xx    x!!!x x!!!!!!     x     =     x x         x      x!!x   xx       ",
   "!!!!x x!!!!!!x  xxx    x!!!!!xx       xxxxxxxxxx     x!!!x x!!xx!     xxxxxxxxxxxxx xx       xx      x!!x  x          ",
   "!!!!x x!!!!!!x         x!!!!!x                      xx!!!x x!!xx!                    xx     xx       x!!x             ",
   "!!!!x x!!!!!!x         x!!!!!x  x xxxx             xx!!!!xyx!!xx!                   xxxxxxx                           ",
   "!!!!x x!!!!!!x         x!!!!!xx       x xx x xxxxxx!!!!!!xx   !                                       xxxx            ",
   "!!!!x x!!!!!!x         x!!!!!!xxx!!!xxxx!!!!!!!!!!!!!!!!!!xx    !                                     x               ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                     "],
   
   
   ["                                                                                                              ",
   "    @            fff                                                                                          ",
   "    xxx                                                                           f                           ",
   "                 xyx                                                                             a            ",
   "                                                                             x   xx   xxxx   xxxxxxx          ",
   "                                        o                                   xx                                ",
   "        xx f                               xx                               xxx                      xxxx       ",
   "          xxx                       xx  xx                              xxxx                                   ",
   "              x x                xx   x                                                                       ",
   "                             xx        x                       xx x  xxx                                      ",
   "                                        x                                                                     ",
   "                   oo   xxx          xxx                                                                      ",
   "                x xxxxx x              x x                           x!!!  xxx                                ",
   "             o                          x x                       x!x!                                         ",
   "             o                            xxx                 x         x                                      ",
   "             o                            x                 x           x       xxx                            ",
   "             o                            x             ff  x           x      x!!!x                           ",
   "             o                            x                 xxxx    xxxx       xxx                            ",
   "                f                       xx     ox   x      x   yy                                             ",
   "         xxx  xxx                    x   xxxxxxxxx   xxxxxxxx              x  x                               ",
   "                                      x   x           x                    x!!!x                              ",
   "           xxx                        x   x           x                     xxx                               ",
   "             xx                      xx   xx   f      x                                                       ",
   "               xx                     x   x= = = =    x            xxx                                        ",
   "                 xx                   x   x           x           x!!!x                                       ",
   "                  xx                  x   x    = = = =x            xxx       xxx                              ",
   "                   xx                xx   xx          x                     x!!!x                             ",
   "                     x xx x xx          x   x           x     x              xxv        xxx                   ",
   "                                      x   x           x              x                 x!!!x                  ",
   "                             xxx xxx xxx xxx          x!!!!!!!!!!!!!!x                   vx                   ",
   "                             x xxx x x xxx x          x!!!!!!!!!!!!!!x                                        ",
   "  ff                         x             x   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "                             xx           xx                                         xxx                      ",
   "  xxx                         x     x     x                                         x!!!x                xxx  ",
   "  x x                         x    xxx    x                                ff        xxx                 x x  ",
   "  x                           x    xxx    xxxxxxx                        xxxxx                             x  ",
   "  x                           x           x                              x   x                             x  ",
   "  x                           xx          x         f          f         x x x                             x  ",
   "  x                                       x       |xxxx|    |xxxx|     xxx xxx                             x  ",
   "  x                xxx                    x                              x         xxx                     x  ",
   "  x               xxxxx       xx          x                             xxx       x!!!x          x         x  ",
   "  x                xxx        x    xxx    x                             x x        xxx          xxx        x  ",
   "  x                xxx        xxxxxxxxxxxxx  x    x    x   x    x     xx xx                    xxx         x  ",
   "  x         f       x         x           x!!x    x!!!!x    x!!!!x    xx   xx                     x         x  ",
   "  xxx  xxxxxx   xxxxxxxxx  xxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxx  xx  x x x   x xxxxxxxxxxxxxx  ",
   "                                                                                  x   x   x   x                ",
   "                                                                                  x           x                ",
   "                                                                                  x     x     x    xxx x       ",
   "                                                                                   x         x         x       ",
   "                                                                                    x       x      xxxxx       ",
   "                                                                                     x     x       x           ",
   "                                                                                       xxx        x xxx       "],
 
 
  ["                                                                             ",
   "                                                                             ",     
   "                                                                             ",
   "                                                                             ",
   "                                                                             ",
   "                                                                             ",
   "                                  @                                          ",
   "                                  x     x  x   x    x  x                     ",
   "                                  x     x  x  x x   x  x                     ",
   "                                  x  x  x  x  x x   x  x                     ",
   "                                  x  x  x  x  x  x  x  x                     ",
   "                                  x x x x  x  x   x x  x                     ",
   "                                  xx   xx  x  x   x x                        ",
   "                                  x     x  x  x    x   x                     ",
   "                                                                             ",
   "                                                                             ",
   "                                                                             ",
   "                                                                             ",
   "                                                                             ",
   "                                                                             ",
   "                                                                             ",
   "                                                                             "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
